version: '2.4'

services:
   db:
     image: linuxserver/mariadb
     volumes:
       - db-data:/var/lib/mysql
     container_name: db
     restart: always
     environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=nextcloud
      - TZ=America/Los_Angeles
      - MYSQL_DATABASE=wordpress 
      - MYSQL_USER=wordpress 
      - MYSQL_PASSWORD=wordpress 
     ports:
       - 3306:3306


   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
      - wp-content:/var/www/html/wp-content
     ports:
       - "8880:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
volumes:
    db-data:
      name: db-datavolume
    wp-content:
      name: wp-data

